name: cocktail-analysis
channels:
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - pip:
    - umap-learn>=0.5.0